### ISSUE TITLE
Zita waring on code thats not really processing.

### ISSUE THREAD

**Issue by afehnker** [creativeprogrammingatelier/atelier-PMD#17]
Zita gives the following warning on programs that are not really processing warning:

`IllegalStateException: field.getFirstDescendant?nterfaceType::class.java) must not be null `

and 

`PMDException: Error while parsing Processing.pde `

That not really graceful.

**Comment by vaxaw0r** [comment]
Two error messages were fixed, however the PMDException was already being handled by us, just with the weird message. I changed the message however not sure if the new one is good enough. Should be more informative.
